version: 2
updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: monthly
    open-pull-requests-limit: 10
    target-branch: dependency-updates
    labels:
      - dependencies
      - python
      - type:maintenance
    ignore:
      - dependency-name: django-mptt # pinned, 0.15 requires Python >= 3.9
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    open-pull-requests-limit: 10
    target-branch: dependency-updates
    labels:
      - dependencies
      - github_actions
      - type:maintenance
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
    open-pull-requests-limit: 10
    target-branch: dependency-updates
    labels:
      - dependencies
      - javascript
      - type:maintenance
