dist: xenial
language: python
cache: pip

addons:
  postgresql: "9.4"

services:
- postgresql
- mysql

python:
- 3.5
- 3.6
- 3.7

env:
- DB=postgres
- DB=mysql
- DB=sqlite3

before_install:
  - sudo apt-get install -y pandoc texlive-xetex texlive-latex-extra texlive-fonts-recommended lmodern

install:
- pip install -e .
- pip install mysqlclient==1.3.14
- pip install psycopg2-binary
- pip install coveralls

before_script:
- sh -c "cp testing/config/settings/$DB.py testing/config/settings/local.py; fi"
- mkdir testing/log

script:
- pytest --cov=rdmo

after_success:
- coveralls
